/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_rasmantuta_ts7800_jni_PeekPoke */

#ifndef _Included_no_rasmantuta_ts7800_jni_PeekPoke
#define _Included_no_rasmantuta_ts7800_jni_PeekPoke
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPoke
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPoke__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPoke
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPoke__IS
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPoke
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPoke__IB
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPeek32
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPeek32
  (JNIEnv *, jclass, jint);

/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPeek16
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPeek16
  (JNIEnv *, jclass, jint);

/*
 * Class:     no_rasmantuta_ts7800_jni_PeekPoke
 * Method:    tsPeek8
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_no_rasmantuta_ts7800_jni_PeekPoke_tsPeek8
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
