/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_rasmantuta_ts7800_jni_ReadAnalog */

#ifndef _Included_no_rasmantuta_ts7800_jni_ReadAnalog
#define _Included_no_rasmantuta_ts7800_jni_ReadAnalog
#ifdef __cplusplus
extern "C" {
#endif
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_0
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_0 1L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_1
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_1 2L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_2
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_2 4L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_3
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_3 8L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_6
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_6 16L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_7
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_7 32L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_0_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_0_INDEX 0L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_1_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_1_INDEX 1L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_2_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_2_INDEX 2L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_3_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_3_INDEX 3L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_6_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_6_INDEX 4L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_7_INDEX
#define no_rasmantuta_ts7800_jni_ReadAnalog_CHANNEL_7_INDEX 5L
#undef no_rasmantuta_ts7800_jni_ReadAnalog_ADC_BASE
#define no_rasmantuta_ts7800_jni_ReadAnalog_ADC_BASE 8.064516E-4f
/*
 * Class:     no_rasmantuta_ts7800_jni_ReadAnalog
 * Method:    tsReadAndAverage
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_no_rasmantuta_ts7800_jni_ReadAnalog_tsReadAndAverage
  (JNIEnv *, jclass, jint);

/*
 * Class:     no_rasmantuta_ts7800_jni_ReadAnalog
 * Method:    tsRawRead
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_no_rasmantuta_ts7800_jni_ReadAnalog_tsRawRead
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
