/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_rasmantuta_ts7800_jni_Watchdog */

#ifndef _Included_no_rasmantuta_ts7800_jni_Watchdog
#define _Included_no_rasmantuta_ts7800_jni_Watchdog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_rasmantuta_ts7800_jni_Watchdog
 * Method:    tsFeed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_Watchdog_tsFeed
  (JNIEnv *, jclass);

/*
 * Class:     no_rasmantuta_ts7800_jni_Watchdog
 * Method:    tsDisable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_Watchdog_tsDisable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
