/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_rasmantuta_ts7800_jni_Util */

#ifndef _Included_no_rasmantuta_ts7800_jni_Util
#define _Included_no_rasmantuta_ts7800_jni_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_rasmantuta_ts7800_jni_Util
 * Method:    tsSetRedLEDOn
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_no_rasmantuta_ts7800_jni_Util_tsSetRedLEDOn
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     no_rasmantuta_ts7800_jni_Util
 * Method:    tsReadOdometer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_rasmantuta_ts7800_jni_Util_tsReadOdometer
  (JNIEnv *, jclass);

/*
 * Class:     no_rasmantuta_ts7800_jni_Util
 * Method:    tsReadBirthDate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_no_rasmantuta_ts7800_jni_Util_tsReadBirthDate
  (JNIEnv *, jclass);

/*
 * Class:     no_rasmantuta_ts7800_jni_Util
 * Method:    tsReadMACAddress
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_no_rasmantuta_ts7800_jni_Util_tsReadMACAddress
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
